// Type tests for scheme-zod-v2 collection functions.
//
// We prove that the schemas generated by z.list(E), z.vector(E), z.array(E)
// project to the right faces:
//
// - Scheme / interpreter face (z.input or SpecInfer scheme projection):
//   used by symbol.native contracts — raw containers (APair|ANil, AVector etc.)
//   that the interpreter actually hands to native impls.
//
// - JS / rosetta face (z.output):
//   used by symbol.rosetta impls — the decoded JS arrays of the element's JS type.
//
// This is the *type-level* counterpart to the higher-level runtime exercising
// done in attestation.test.ts (which walks real pair/vector spines produced
// through full rosetta + membrane using mostly z.value contracts).
//
// These tests use the same Face machinery (_bake.ts) that real contracts rely on.

import { describe, expectTypeOf, test } from "vitest";

import * as z from "../scheme-zod-v2.js";
import type { APair } from "../../values/primitives/APair.js";
import type { ANil } from "../../values/primitives/ANil.js";
import type { ACharacter } from "../../values/primitives/ACharacter.js";
import type { AString } from "../../values/primitives/AString.js";
import type { ABool } from "../../values/primitives/ABool.js";
import type { AVector } from "../../values/primitives/AVector.js";
import type { AJSArray } from "../../values/primitives/AJSArray.js";
import type { SchemeValue } from "../../values/types.js";
import { type DecodedArgs, type SpecInfer } from "../symbols/_bake.js";

// Helpers mirroring the Face logic used for contracts.
type SchemeFace<S extends z.ZodTypeAny> = z.input<S>;
type JSFace<S extends z.ZodTypeAny> = z.output<S>;

describe("scheme-zod-v2 collection faces (interpreter vs JS)", () => {
  test("z.list(E) — homogeneous", () => {
    const charList = z.list(z.char);

    // Scheme (native) face: the interpreter container (APair is generic in the model)
    type S = SchemeFace<typeof charList>;
    expectTypeOf<S>().toExtend<APair<any, any> | ANil>();

    // JS (rosetta) face: array of the element's JS image
    type J = JSFace<typeof charList>;
    expectTypeOf<J>().toExtend<string[]>();

    // Via the contract helpers (what actual symbol.native defs see — the SCHEME face)
    expectTypeOf<DecodedArgs<[typeof charList], "scheme">>().toExtend<[APair<any, any> | ANil]>();
    expectTypeOf<SpecInfer<typeof charList>>().toExtend<string[]>();
  });

  test("z.cons(car, cdr) — the dotted-pair form", () => {
    const consShape = z.cons(z.char, z.union([z.nil, z.boolean]));

    type S = SchemeFace<typeof consShape>;
    expectTypeOf<S>().toExtend<APair<any, any>>(); // the container

    type J = JSFace<typeof consShape>;
    // tuple of the two JS faces
    expectTypeOf<J>().toExtend<[string, null | boolean]>();
  });

  test("z.vector(E) and z.array(E)", () => {
    const boolVec = z.vector(z.boolean);
    type VS = SchemeFace<typeof boolVec>;
    type VJ = JSFace<typeof boolVec>;
    // vector container on scheme side (the union type in practice)
    expectTypeOf<VS>().toExtend<AVector | AJSArray>();
    expectTypeOf<VJ>().toEqualTypeOf<boolean[]>();

    // z.array is now zod's own plain array (NOT a scheme list/vector union): a plain array of
    // the AString codec — scheme face is AString[], JS face is string[].
    const strArr = z.array(z.string);
    type AS = SchemeFace<typeof strArr>;
    type AJ = JSFace<typeof strArr>;
    expectTypeOf<AS>().toExtend<AString[]>();
    expectTypeOf<AJ>().toExtend<string[]>();
  });

  test("nested and complex elements", () => {
    const listOfLists = z.list(z.list(z.char));
    type J = JSFace<typeof listOfLists>;
    expectTypeOf<J>().toExtend<string[][]>();

    // element that is itself a union including nil (common for list tails)
    const weird = z.list(z.union([z.char, z.nil, z.boolean]));
    type JW = JSFace<typeof weird>;
    expectTypeOf<JW>().toExtend<(string | null | boolean)[]>();
  });

  test("using with real contract shapes (mirrors env/r7rs usage)", () => {
    // A typical "list input, vector output" shape
    const listInVecOut = {
      input: [z.list(z.value)],
      output: [z.vector(z.value)],
    } as const;

    // Native impls receive the SCHEME face (raw containers); rosetta impls the JS face.
    type In = DecodedArgs<typeof listInVecOut.input, "scheme">;
    type Out = DecodedArgs<typeof listInVecOut.output>;

    expectTypeOf<In>().toExtend<[APair<any, any> | ANil]>();
    // NOT `any[]` — that's vacuous (any[] accepts almost anything, so this would pass
    // even if the decode type were wrong). z.vector(z.value)'s JS face is SchemeValue[].
    expectTypeOf<Out>().toExtend<[SchemeValue[]]>();
  });

  test("z.list() (any) is still usable as before", () => {
    const anyL = z.list();
    type S = SchemeFace<typeof anyL>;
    expectTypeOf<S>().toExtend<APair<any, any> | ANil>();

    type J = JSFace<typeof anyL>;
    expectTypeOf<J>().toExtend<SchemeValue[]>();
  });
});
